version: '3'

services:
  traefik:
    image: traefik:1.5.4
    container_name: traefik
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data_traefik_toml:/traefik.toml
      - data_traefik_acmejson:/acme.json

    whoami:
      image: "traefik/whoami"
      container_name: "simple-service"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
        - "traefik.http.routers.whoami.entrypoints=web"

networks:
  web:
    external: true

volumes:
  data_traefik_toml:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bond'
      device: '/home/mickael/traefik/traefik.toml'
  data_traefik_acmejson:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bond'
      device: '/home/mickael/traefik/acme.json'
    